Bil372_Homework/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Bil372_Homework.Models
{
    public class User
    {
        [Key]
        public int AuthenticationID { get; set; }
        [StringLength(20)]
        public String UserName { get; set; }
        [StringLength(50)]
        public String Password { get; set; }
        public int Confirm { get; set; }
    }

    public class UserViewModel
    {
        public List<User> Users{ get; set; }
        public UserViewModel()
        {
            Users = new List<User>();
        }
    }
}

Bil372_Homework/Controllers/ConferenceController.cs
using Bil372_Homework.Data;
using Bil372_Homework.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bil372_Homework.Controllers
{
    public class ConferenceController : Controller
    {

        public String ConnectionString = "Server=tcp:databaseadmin.database.windows.net,1433;Initial Catalog=Bil372HW;Persist Security Info=False;User ID=databaseadmin;Password=admindatabase_9;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;";


        // GET: Conference
        public ActionResult Index()
        {
            DataTable dataTable = new DataTable();
            using (SqlConnection sqlCon = new SqlConnection(ConnectionString))
            {
                sqlCon.Open();
                SqlDataAdapter sqlDA = new SqlDataAdapter("SELECT * FROM [dbo].[Conferences] WHERE CreatorUser = " + LoggedUser.LoggedId  , sqlCon);
                sqlDA.Fill(dataTable);
            }
            return View(dataTable);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new Conference());
        }

        [HttpPost]
        public ActionResult Create(Conference conference)
        {
            using(SqlConnection sqlCon = new SqlConnection(ConnectionString))
            {
                sqlCon.Open();
                string query = "INSERT INTO [dbo].[Conferences] VALUES('_" + conference.ShortName + "_" + conference.Year + "', '" + conference.CreationDateTime + "','" +
                    conference.Name + "','" + conference.ShortName + "'," + conference.Year + ",'" + conference.StartDate + "','" + conference.EndDate + "','" + 
                    conference.SubmisionDeadline + "'," + LoggedUser.LoggedId + ",'" + conference.WebSite + "')";
                SqlCommand sqlCommand = new SqlCommand(query,sqlCon);
                sqlCommand.ExecuteNonQuery();
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(String ConfID)
        {
            Conference conference = new Conference();
            DataTable dtable = new DataTable();
            //ConfID = ConfID.Substring(1, ConfID.Length - 1);
            using (SqlConnection sqlCon = new SqlConnection(ConnectionString))
            {
                sqlCon.Open();
                string query = "SELECT * FROM [dbo].[Conferences] WHERE ConfID ='"  + ConfID + "'";
                SqlDataAdapter sqlDa = new SqlDataAdapter(query, sqlCon);
                sqlDa.Fill(dtable);
                if(dtable.Rows.Count == 1)
                {
                    conference.ConfID = dtable.Rows[0][0].ToString();
                    conference.CreationDateTime = Convert.ToDateTime(dtable.Rows[0][1].ToString());
                    conference.Name = dtable.Rows[0][2].ToString();
                    conference.ShortName= dtable.Rows[0][3].ToString();
                    conference.Year = Convert.ToInt32(dtable.Rows[0][4].ToString());
                    conference.StartDate = Convert.ToDateTime(dtable.Rows[0][5].ToString());
                    conference.EndDate= Convert.ToDateTime(dtable.Rows[0][6].ToString());
                    conference.SubmisionDeadline= Convert.ToDateTime(dtable.Rows[0][7].ToString());
                    conference.CreatorUser = Convert.ToInt32(dtable.Rows[0][8].ToString());
                    conference.WebSite = dtable.Rows[0][9].ToString();
                    return View(conference);
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(Conference conference)
        {
            using (SqlConnection sqlCon = new SqlConnection(ConnectionString))
            {
                sqlCon.Open();
                string query = "UPDATE [dbo].[Conferences] SET CreationDateTime = '" + conference.CreationDateTime + "',Name = '" +
                    conference.Name + "', ShortName = '" + conference.ShortName + "',Year = " + conference.Year + ", StartDate ='" + conference.StartDate + "',EndDate = '" + conference.EndDate + "', SubmisionDeadline = '" +
                    conference.SubmisionDeadline + "',WebSite = '" + conference.WebSite + "' WHERE ConfID = '" + conference.ConfID + "'";
                SqlCommand sqlCmd = new SqlCommand(query, sqlCon);
                sqlCmd.ExecuteNonQuery();
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(String ConfID)
        {
            using(SqlConnection sqlCon = new SqlConnection(ConnectionString))
            {
                sqlCon.Open();
                string query = "DELETE FROM [dbo].[ConferenceRoles] WHERE ConfID = ' " + ConfID + "'";
                SqlCommand sqlCommand1 = new SqlCommand(query, sqlCon);
                sqlCommand1.ExecuteNonQuery();
                query = "DELETE FROM [dbo].[Conferences] WHERE ConfID = '" + ConfID + "'";
                SqlCommand sqlCommand = new SqlCommand(query, sqlCon);
                sqlCommand.ExecuteNonQuery();
                
            }
            return RedirectToAction("Index");
        }

    }
}

Bil372_Homework/Controllers/UserController.cs
using Bil372_Homework.Data;
using Bil372_Homework.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bil372_Homework.Controllers
{
    public class UserController : Controller
    {
        SqlConnection con = new SqlConnection();
        SqlCommand com = new SqlCommand();
        SqlDataReader dr;

        private AppDbContext dbContext;
        public UserController()
        {
            dbContext = new AppDbContext("Server=tcp:databaseadmin.database.windows.net,1433;Initial Catalog=Bil372HW;Persist Security Info=False;User ID=databaseadmin;Password=admindatabase_9;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;");
        }

        // GET: User
        [HttpGet]
        public ActionResult Login()
        {
            var viewModel = new UserViewModel();
            viewModel.Users = dbContext.Users.ToList();
            return View(viewModel);
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SignIn()
        {
            return View();
        }

        public ActionResult Info()
        {
            connectionString();
            con.Open();
            com.Connection = con;
            List<UserInfo> model = new List<UserInfo>();
            com.CommandText = "SELECT * FROM [dbo].[UserInfoes] WHERE AuthenticationID = (SELECT AuthenticationID FROM [dbo].[Users] Where UserName ='" + LoggedUser.LoggedUserName + "' and Password ='" + LoggedUser.LoggedPassword + "')";
            dr = com.ExecuteReader();
            if (dr.Read())
            {
                var UserInf = new UserInfo();
                UserInf.AuthenticationID = (int)dr["AuthenticationID"];
                UserInf.Title = dr["Title"].ToString();
                UserInf.Name = dr["Name"].ToString();
                UserInf.Affilation = dr["Affilation"].ToString();
                UserInf.primaryEmail = dr["primaryEmail"].ToString();
                UserInf.secondaryEmail = dr["secondaryEmail"].ToString();
                UserInf.password = dr["password"].ToString();
                UserInf.Phone = dr["Phone"].ToString();
                UserInf.fax = dr["fax"].ToString();
                UserInf.URL = dr["URL"].ToString();
                UserInf.Address = dr["Address"].ToString();
                UserInf.City = dr["City"].ToString();
                UserInf.Country = dr["Country"].ToString();
                UserInf.Record = dr["Record"].ToString();
                UserInf.CreationDate = (DateTime)dr["CreationDate"];
                model.Add(UserInf);

            }
            con.Close();
            return View(model);
        }

        void connectionString()
        {
            con.ConnectionString = "Server=tcp:databaseadmin.database.windows.net,1433;Initial Catalog=Bil372HW;Persist Security Info=False;User ID=databaseadmin;Password=admindatabase_9;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;";
        }

        [HttpPost]
        public ActionResult Verify(User user)
        {
            connectionString();
            con.Open();
            com.Connection = con;
            com.CommandText = "SELECT AuthenticationID, Confirm FROM [dbo].[Users] WHERE UserName ='" + user.UserName + "' and Password ='" + user.Password + "'";
            dr = com.ExecuteReader();
            if (dr.Read())
            {
                int Confirm = (int)dr["Confirm"];
                if(Confirm == 0)
                {
                    con.Close();
                    return View("NotConfirm");
                }
                dr.Close();

                List<UserInfo> model = new List<UserInfo>();
                com.CommandText = "SELECT * FROM [dbo].[UserInfoes] WHERE AuthenticationID = (SELECT AuthenticationID FROM [dbo].[Users] Where UserName ='" + user.UserName + "' and Password ='" + user.Password + "')";
                dr = com.ExecuteReader();
                if (dr.Read())
                {
                    var UserInf = new UserInfo();
                    UserInf.AuthenticationID = (int)dr["AuthenticationID"];
                    LoggedUser.LoggedId = (int)dr["AuthenticationID"];
                    UserInf.Title = dr["Title"].ToString(); 
                    UserInf.Name = dr["Name"].ToString(); 
                    UserInf.Affilation = dr["Affilation"].ToString(); 
                    UserInf.primaryEmail = dr["primaryEmail"].ToString(); 
                    UserInf.secondaryEmail = dr["secondaryEmail"].ToString(); 
                    UserInf.password = dr["password"].ToString(); 
                    UserInf.Phone = dr["Phone"].ToString(); 
                    UserInf.fax = dr["fax"].ToString(); 
                    UserInf.URL = dr["URL"].ToString(); 
                    UserInf.Address = dr["Address"].ToString(); 
                    UserInf.City = dr["City"].ToString(); 
                    UserInf.Country = dr["Country"].ToString(); 
                    UserInf.Record = dr["Record"].ToString(); 
                    UserInf.CreationDate = (DateTime)dr["CreationDate"];
                    model.Add(UserInf);

                }
                LoggedUser.LoggedUserName = user.UserName;
                LoggedUser.LoggedPassword = user.Password;
                con.Close();
                if(LoggedUser.LoggedUserName ==  "admin")
                {
                    DataTable dataTable = new DataTable();
                    using (SqlConnection sqlCon = new SqlConnection("Server=tcp:databaseadmin.database.windows.net,1433;Initial Catalog=Bil372HW;Persist Security Info=False;User ID=databaseadmin;Password=admindatabase_9;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"))
                    {
                        sqlCon.Open();
                        SqlDataAdapter sqlDA = new SqlDataAdapter("SELECT * FROM [dbo].[Users]", sqlCon);
                        sqlDA.Fill(dataTable);
                    }
                    return View("Admin", dataTable);
                }
                return View("Info",model);
            }
            else
            {
                con.Close();
                return RedirectToAction("Login");
            }
        }

        [HttpPost]
        public ActionResult CreateUser(User user)
        {
            connectionString();
            con.Open();
            com.Connection = con;
            com.CommandText = "INSERT INTO [dbo].[Users] VALUES( '" + user.UserName + "', '" + user.Password + "', " + 0 + ")";
            com.ExecuteNonQuery();
            com.CommandText = "SELECT AuthenticationID FROM [dbo].[Users] Where UserName ='" + user.UserName + "' and Password ='" + user.Password + "'";
            dr = com.ExecuteReader();
            int authenticationId = 0;
            while (dr.Read())
            {
                authenticationId = (int)dr["AuthenticationID"]; 
            }
            dr.Close();
            com.CommandText = "INSERT INTO [dbo].[UserInfoes] VALUES ('"+ authenticationId +"','','','','','','" + user.Password + "' , '','','','','','','','')";
            com.ExecuteNonQuery();
            con.Close();
            return View("Login");
        }
        [HttpGet,HttpPost]
        public ActionResult IInfo()
        {
            connectionString();
            con.Open();
            com.Connection = con;
            List<UserInfo> model = new List<UserInfo>();
            com.CommandText = "SELECT * FROM [dbo].[UserInfoes] WHERE AuthenticationID = (SELECT AuthenticationID FROM [dbo].[Users] Where UserName ='" + LoggedUser.LoggedUserName + "' and Password ='" + LoggedUser.LoggedPassword + "')";
            dr = com.ExecuteReader();
            if (dr.Read())
            {
                    var UserInf = new UserInfo();
                    UserInf.AuthenticationID = (int)dr["AuthenticationID"];
                    UserInf.Title = dr["Title"].ToString();
                    UserInf.Name = dr["Name"].ToString();
                    UserInf.Affilation = dr["Affilation"].ToString();
                    UserInf.primaryEmail = dr["primaryEmail"].ToString();
                    UserInf.secondaryEmail = dr["secondaryEmail"].ToString();
                    UserInf.password = dr["password"].ToString();
                    UserInf.Phone = dr["Phone"].ToString();
                    UserInf.fax = dr["fax"].ToString();
                    UserInf.URL = dr["URL"].ToString();
                    UserInf.Address = dr["Address"].ToString();
                    UserInf.City = dr["City"].ToString();
                    UserInf.Country = dr["Country"].ToString();
                    UserInf.Record = dr["Record"].ToString();
                    UserInf.CreationDate = (DateTime)dr["CreationDate"];
                    model.Add(UserInf);

            }
            con.Close();
            return View(model);
        }

        [HttpPost]
        public ActionResult UpdateUser(UserInfo userInfo)
        {
            connectionString();
            con.Open();
            com.Connection = con;
            com.CommandText = "UPDATE [dbo].[UserInfoes] SET Title = '" + userInfo.Title + "', Name = '" + userInfo.Name + "', Affilation = '" + userInfo.Affilation + "', primaryEmail = '" + userInfo.primaryEmail + "', secondaryEmail = '" + userInfo.secondaryEmail +
                "', password = '" + userInfo.password + "', Phone = '" + userInfo.Phone + "', fax = '" + userInfo.fax + "', URL = '" + userInfo.URL + "', Address = '" + userInfo.Address + "', City = '" + userInfo.City + "', Country = '" + userInfo.Country + "', Record = '" + userInfo.Record +
                "' WHERE AuthenticationID = " + userInfo.AuthenticationID;
            com.ExecuteNonQuery();
            con.Close();

            connectionString();

Bil372_Homework/Views/User/AddOrEdit.cshtml
@model Bil372_Homework.Models.Conference
@{
	Layout = null;
}

@using (Html.BeginForm("AddOrEdit", "Conference", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" }))
{
		@Html.HiddenFor(model => model.ConfID)
	<div class="form-group">
		@Html.LabelFor(model => model.Name, new { @class = "control-label" })
		@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
		@Html.ValidationMessageFor(model => model.Name)
	</div>
	<div class="form-group">
		@Html.LabelFor(model => model.ShortName, new { @class = "control-label" })
		@Html.EditorFor(model => model.ShortName, new { htmlAttributes = new { @class = "form-control" } })
		@Html.ValidationMessageFor(model => model.ShortName)
	</div>
	<div class="form-group">
		@Html.LabelFor(model => model.StartDate, new { @class = "control-label" })
		@Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
	</div>
	<div class="form-group">
		@Html.LabelFor(model => model.EndDate, new { @class = "control-label" })
		@Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
	</div>
	<div class="form-group">
		@Html.LabelFor(model => model.SubmisionDeadline, new { @class = "control-label" })
		@Html.EditorFor(model => model.SubmisionDeadline, new { htmlAttributes = new { @class = "form-control" } })
	</div>
	<div class="form-group">

		@Html.LabelFor(model => model.CreatorUser, new { @class = "control-label" })
		<div class="input-group">
			<span class="input-group-addon">CreatorUser</span>
			@Html.EditorFor(model => model.CreatorUser, new { htmlAttributes = new { @class = "form-control" } })
		</div>
	</div>

	<div class="form-group">
		<input type="submit" value="Submit" class="btn btn-primary" />
		<input type="reset" value="Reset" class="btn" />
	</div>
}

Bil372_Homework/Views/User/Admin.cshtml
@model System.Data.DataTable
@{
	ViewBag.Title = "Admin";
	Layout = "~/Views/_LayoutPage1.cshtml";
}

<h2>Users</h2>
<head>

	<script src="~/Scripts/bootstrap.min.js"></script>
	<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>

<table class=" table table-bordered table-striped table-hover">
	<tr>
		<th>User ID</th>
		<th>User Name</th>
		<th>Confirm</th>
		<th></th>
	</tr>

	@for (int i = 0; i < Model.Rows.Count; i++)
	{
		<tr>
			<td> @Model.Rows[i][0]</td>
			<td> @Model.Rows[i][1]</td>
			<td> @Model.Rows[i][3]</td>
			<td>
				<a href="@Url.Action("Confirm", "User",  new { @AuthenticationID = @Model.Rows[i][0]})"> Confirm</a>
			</td>
		</tr>
	}
</table>

Bil372_Homework/Views/User/Info.cshtml
@model IEnumerable<Bil372_Homework.Models.UserInfo>
@{
	Layout = "~/Views/_LayoutPage1.cshtml";
}

<!DOCTYPE html>

<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<style>
		body {
			font-family: Arial, Helvetica, sans-serif;
			background-color: black;
		}

		* {
			box-sizing: border-box;
		}

		/* Add padding to containers */
		.container {
			padding: 16px;
			background-color: white;
		}

		/* Full-width input fields */
		input[type=text], input[type=password] {
			width: 100%;
			padding: 15px;
			margin: 5px 0 22px 0;
			display: inline-block;
			border: none;
			background: #f1f1f1;
		}

			input[type=text]:focus, input[type=password]:focus {
				background-color: #ddd;
				outline: none;
			}

		/* Overwrite default styles of hr */
		hr {
			border: 1px solid #f1f1f1;
			margin-bottom: 25px;
		}

		/* Set a style for the submit button */
		.registerbtn {
			background-color: #4CAF50;
			color: white;
			padding: 16px 20px;
			margin: 8px 0;
			border: none;
			cursor: pointer;
			width: 100%;
			opacity: 0.9;
		}

			.registerbtn:hover {
				opacity: 1;
			}

		/* Add a blue text color to links */
		a {
			color: dodgerblue;
		}

		/* Set a grey background color and center the text of the "sign in" section */
		.signin {
			background-color: #f1f1f1;
			text-align: center;
		}
	</style>
</head>
<body>
	<form action="UpdateUser" method="POST">
		<div class="container">

			@foreach (var item in Model)
			{
				<h1>User Info</h1>
				<p>You can alter your user info</p>
				<hr>

				<label for="AuthenticationID"><b>AuthenticationID</b></label>
				<input type="text" name="AuthenticationID" id="AuthenticationID" value=@item.AuthenticationID readonly>

				<label for="Title"><b>Title</b></label>
				<input type="text" name="Title" id="Title" value=@item.Title>

				<label for="Name"><b>Name</b></label>
				<input type="text" name="Name" id="Name" value=@item.Name>

				<label for="Password"><b>Password</b></label>
				<input type="text" name="Password" id="Password" value=@item.password>

				<label for="Affilation"><b>Affilation</b></label>
				<input type="text" name="Affilation" id="Affilation" value=@item.Affilation>

				<label for="primaryEmail"><b>Primary E-mail</b></label>
				<input type="text" name="primaryEmail" id="primaryEmail" value=@item.primaryEmail>

				<label for="secondaryEmail"><b>Secondary E-mail</b></label>
				<input type="text" name="secondaryEmail" id="secondaryEmail" value=@item.secondaryEmail>

				<label for="Phone"><b>Phone</b></label>
				<input type="text" name="Phone" id="Phone" value=@item.Phone>

				<label for="Fax"><b>Fax</b></label>
				<input type="text" name="fax" id="Fax" value=@item.fax>

				<label for="URL"><b>URL</b></label>
				<input type="text" name="URL" id="URL" value=@item.URL>

				<label for="Address"><b>Address</b></label>
				<input type="text" name="Address" id="Address" value=@item.Address>

				<label for="City"><b>City</b></label>
				<input type="text" name="City" id="City" value=@item.City>

				<label for="Country"><b>Country</b></label>
				<input type="text" name="Country" id="Country" value=@item.Country>

				<label for="Record"><b>Record</b></label>
				<input type="text" name="Record" id="Record" value=@item.Record>

				<hr>
			}
			<button type="submit" class="registerbtn">Save</button>
		</div>
	</form>

</body>

Bil372_Homework/Views/User/Login.cshtml
@{
	ViewBag.Title = "Login";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<title> Login Page </title>
<style>
	Body {
		font-family: Calibri, Helvetica, sans-serif;
		background-color: hsla(89, 43%, 51%, 0.3);
	}

	button {
		background-color: #4CAF50;
		width: 100%;
		color: orange;
		padding: 15px;
		margin: 10px 0px;
		border: none;
		cursor: pointer;
	}

	form {
		border: 3px solid #f1f1f1;
	}

	input[type=text], input[type=password] {
		width: 100%;
		margin: 8px 0;
		padding: 12px 20px;
		display: inline-block;
		border: 2px solid green;
		box-sizing: border-box;
	}

	button:hover {
		opacity: 0.7;
	}



	.container {
		padding: 25px;
		background-color: lightblue;
	}
</style>
<center> <h1> Login Page </h1> </center>
<form action="Verify" method="post">
	<div class="container">
		<label>Username : </label>
		<input type="text" placeholder="Enter Username" name="UserName" required>
		<label>Password : </label>
		<input type="password" placeholder="Enter Password" name="Password" required>
		<button type="submit">Login</button>
		<li><a href="SignIn">New Admin Account</a></li>
	</div>
</form>

Bil372_Homework/Views/User/NotConfirm.cshtml
@{
	ViewBag.Title = "NotConfirm";
}

<style>
	.content {
		max-width: 500px;
		margin: auto;
	}
</style>
<body>

	<div class="content">
		<h1>Admin Onayı gerçekleşmedi !</h1>
		<a href="Login">Back to Login</a>.</p>
	</div>

</body>

Bil372_Homework/Views/User/SignIn.cshtml
@{
	ViewBag.Title = "SignIn";
	Layout = "~/Views/_LayoutPage1.cshtml";
}

<!DOCTYPE html>

<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<style>
		body {
			font-family: Arial, Helvetica, sans-serif;
			background-color: black;
		}

		* {
			box-sizing: border-box;
		}

		/* Add padding to containers */
		.container {
			padding: 16px;
			background-color: white;
		}

		/* Full-width input fields */
		input[type=text], input[type=password] {
			width: 100%;
			padding: 15px;
			margin: 5px 0 22px 0;
			display: inline-block;
			border: none;
			background: #f1f1f1;
		}

			input[type=text]:focus, input[type=password]:focus {
				background-color: #ddd;
				outline: none;
			}

		/* Overwrite default styles of hr */
		hr {
			border: 1px solid #f1f1f1;
			margin-bottom: 25px;
		}

		/* Set a style for the submit button */
		.registerbtn {
			background-color: #4CAF50;
			color: white;
			padding: 16px 20px;
			margin: 8px 0;
			border: none;
			cursor: pointer;
			width: 100%;
			opacity: 0.9;
		}

			.registerbtn:hover {
				opacity: 1;
			}

		/* Add a blue text color to links */
		a {
			color: dodgerblue;
		}

		/* Set a grey background color and center the text of the "sign in" section */
		.signin {
			background-color: #f1f1f1;
			text-align: center;
		}
	</style>
</head>
<body>

	<form action="CreateUser" method="POST">
		<div class="container">
			<h1>Register</h1>
			<p>Please fill in this form to create an account.</p>
			<hr>

			<label for="person_name"><b>UserName</b></label>
			<input type="text" placeholder="Enter Name or Email" name="UserName" id="UserName" required>

			<label for="person_password"><b>Password</b></label>
			<input type="password" placeholder="Enter Password" name="Password" id="Password" required>

			<hr>

			<button type="submit" class="registerbtn">Register</button>
		</div>

		<div class="container signin">
			<p>Already have an account? <a href="Login">Sign in</a>.</p>
		</div>
	</form>

</body>

Bil372_Homework/Views/User/UserConference.cshtml
@{
	ViewBag.Title = "UserConference";
}



<h2>Confefrence</h2>

<a class="btn btn-success" style="margin-bottom:10px" onclick="PopupForm('@Url.Action("AddOrEdit","User")')"><i class="fa fa-plus"></i> Add New</a>
<table id="ConferenceTable" class="table table-striped table-bordered" style="width:100%">
	<thead>
		<tr>
			<th>ConfID</th>
			<th>Name</th>
			<th>Short Name</th>
			<th>Start Date</th>
			<th>End Date</th>
			<th></th>
		</tr>
	</thead>
</table>

<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

@section scripts{
	<script src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>

	<script>
        var Popup, dataTable;
        $(document).ready(function () {
			dataTable = $("#ConferenceTable").DataTable({
                "ajax": {
                    "url": "/User/GetData",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "ConfID" },
					{ "data": "Name" },
					{ "data": "ShortName" },
					{ "data": "StartDate" },
					{ "data": "EndDate" },
                    {"data":"SubmisionDeadline" , "render" : function (data) {
                        return "<a class='btn btn-default btn-sm' onclick=PopupForm('@Url.Action("AddOrEdit","User")/" + data + "')><i class='fa fa-pencil'></i> Edit</a><a class='btn btn-danger btn-sm' style='margin-left:5px' onclick=Delete("+data+")><i class='fa fa-trash'></i> Delete</a>";
                    },
                        "orderable": false,
                        "searchable":false,
                        "width":"150px"
                    }

                ],
                "language": {

                    "emptyTable" : "No data found, Please click on <b>Add New</b> Button"
                }
            });
        });

        function PopupForm(url) {
            var formDiv = $('<div/>');
            $.get(url)
            .done(function (response) {
                formDiv.html(response);

                Popup = formDiv.dialog({
                    autoOpen: true,
                    resizable: false,
                    title: 'Fill Conference Details',
                    height: 500,
                    width: 700,
                    close: function () {
                        Popup.dialog('destroy').remove();
                    }

                });
            });
        }

        function SubmitForm(form) {
            $.validator.unobtrusive.parse(form);
            if($(form).valid()){
                $.ajax({
                    type : "POST",
                    url : form.action,
                    data : $(form).serialize(),
                    success : function (data) {
                        if(data.success)
                        {
                            Popup.dialog('close');
                            dataTable.ajax.reload();

                            $.notify(data.message,{
                                globalPosition :"top center",
                                className : "success"
                            })

                        }
                    }
                });
            }
            return false;
        }

        function Delete(id) {
            if(confirm('Are You Sure to Delete this Conference Record ?'))
            {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete","User")/' + id,
                    success: function (data) {
                        if (data.success)
                        {
                            dataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            })

                        }
                    }

                });
            }
        }
	</script>
}